import type { Apartment, LocationFeature, Testimonial, Service } from "./interface"

export const featuredApartments: Apartment[] = [
  {
    id: "apt-001",
    imageUrl: "/images/image1.png",
    name: "Luxury City View Apartment",
    location: "Victoria Island, Lagos",
    price: 25000,
    rating: 4.8,
    guests: 4,
    beds: 2,
    baths: 2,
  },
  {
    id: "apt-002",
    imageUrl: "/images/image8.png",
    name: "Modern Downtown Loft",
    location: "Wuse 2, Abuja",
    price: 25000,
    rating: 4.5,
    guests: 2,
    beds: 1,
    baths: 1,
  },
  {
    id: "apt-003",
    imageUrl: "/images/image12.png",
    name: "Cozy Family Retreat",
    location: "Trans Amadi, Port Harcourt",
    price: 250,
    rating: 4.3,
    guests: 6,
    beds: 3,
    baths: 2,
  },
  {
    id: "apt-004",
    imageUrl: "/images/image6.png",
    name: "Spacious Balcony Suite",
    location: "Lekki Phase 1, Lagos",
    price: 300,
    rating: 4.9,
    guests: 5,
    beds: 3,
    baths: 3,
  },
]

export const locationFeatures: LocationFeature[] = [
  {
    id: "loc-001",
    imageUrl: "/images/image5.jpg",
    altText: "Lagos city skyline",
    locationName: "Lagos",
    apartmentCount: 120,
    colSpan: 1,
  },
  {
    id: "loc-002",
    imageUrl: "/images/image9.jpg",
    altText: "Abuja city view",
    locationName: "Abuja",
    apartmentCount: 85,
    colSpan: 1,
  },
  {
    id: "loc-003",
    imageUrl: "/images/image10.jpg",
    altText: "Port Harcourt waterfront",
    locationName: "Port Harcourt",
    apartmentCount: 50,
    colSpan: 2,
  },
  {
    id: "loc-004",
    imageUrl: "/images/image14.jpg",
    altText: "Enugu green landscape",
    locationName: "Enugu",
    apartmentCount: 30,
    colSpan: 2,
  },
  {
    id: "loc-005",
    imageUrl: "/images/image3.jpg",
    altText: "Calabar carnival street",
    locationName: "Calabar",
    apartmentCount: 40,
    colSpan: 1,
  },
  {
    id: "loc-006",
    imageUrl: "/images/image2.jpg",
    altText: "Ibadan brown roofs",
    locationName: "Ibadan",
    apartmentCount: 60,
    colSpan: 1,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "test-001",
    rating: 5,
    text: "The apartment was absolutely stunning and exceeded all our expectations. Clean, spacious, and perfectly located. Highly recommend Jenrianna-apartments!",
    authorName: "Aisha Bello",
    authorImage: "/placeholder.svg?height=40&width=40&text=Aisha",
  },
  {
    id: "test-002",
    rating: 5,
    text: "Seamless booking process and a fantastic stay. The amenities were top-notch, and the host was incredibly responsive. Will definitely book again!",
    authorName: "Chukwudi Okoro",
    authorImage: "/placeholder.svg?height=40&width=40&text=Chukwudi",
  },
  {
    id: "test-003",
    rating: 5,
    text: "A true home away from home! The apartment was beautifully furnished and had everything we needed. Great value for money and a comfortable experience.",
    authorName: "Fatima Adebayo",
    authorImage: "/placeholder.svg?height=40&width=40&text=Fatima",
  },
]

export const trendingApartments: Apartment[] = [
  {
    id: "trend-001",
    imageUrl: "/images/image7.png",
    name: "Chic Studio in Ikoyi",
    location: "Ikoyi, Lagos",
    price: 190,
    rating: 4.7,
    guests: 2,
    beds: 1,
    baths: 1,
  },
  {
    id: "trend-002",
    imageUrl: "/images/image11.png",
    name: "Family Suite in Maitama",
    location: "Maitama, Abuja",
    price: 220,
    rating: 4.6,
    guests: 5,
    beds: 3,
    baths: 2,
  },
  {
    id: "trend-003",
    imageUrl: "/images/image12.png",
    name: "Executive Penthouse",
    location: "Victoria Island, Lagos",
    price: 350,
    rating: 4.9,
    guests: 4,
    beds: 2,
    baths: 2,
  },
  {
    id: "trend-004",
    imageUrl: "/images/image6.png",
    name: "Riverside View Flat",
    location: "Old GRA, Port Harcourt",
    price: 160,
    rating: 4.4,
    guests: 3,
    beds: 2,
    baths: 1,
  },
]


export const detailedApartments: Apartment[] = [
  {
    id: "1",
    name: "Luxury Suite",
    location: "Downtown, New York",
    price: 250,
    rating: 4.5,
    imageUrl: "/img1.jpg",
    guests: 4,
    beds: 2,
    baths: 2,
    description: "A luxurious suite in the heart of the city with stunning views.",
    galleryImages: [
      { id: "img1", src: "/img1.jpg", alt: "Main view", isLarge: true },
      { id: "img2", src: "/img2.jpg", alt: "Bedroom" },
      { id: "img3", src: "/img3.jpg", alt: "Living room" },
    ],
    amenities: [
      { id: "1", name: "Wifi", icon: "Wifi" },
      { id: "2", name: "Air Conditioning", icon: "AirVent" },
      { id: "3", name: "Kitchen", icon: "Utensils" },
    ],
  },
  {
    id: "2",
    name: "Cozy Retreat",
    location: "Brooklyn, New York",
    price: 150,
    rating: 4.2,
    imageUrl: "/img4.jpg",
    guests: 2,
    beds: 1,
    baths: 1,
    description: "A cozy apartment perfect for a weekend getaway.",
    galleryImages: [
      { id: "img4", src: "/img4.jpg", alt: "Main view", isLarge: true },
      { id: "img5", src: "/img5.jpg", alt: "Bedroom" },
    ],
    amenities: [
      { id: "4", name: "Wifi", icon: "Wifi" },
      { id: "5", name: "TV", icon: "Tv" },
    ],
  },
];

export const services: Service[] = [
  {
    id: 'private-chef',
    name: 'Private Chef',
    description: 'Enjoy meals prepared by a personal chef',
    price: 15000,
    unit: '/night',
  },
  {
    id: 'airport-transfer',
    name: 'Airport Transfer',
    description: 'Hassle-free pick-up and drop-off at the airport',
    price: 5000,
    unit: '/trip',
  },
  {
    id: 'daily-cleaning',
    name: 'Daily Cleaning',
    description: 'Keep your apartment spotless throughout your stay',
    price: 3000,
    unit: '/day',
  },
  {
    id: 'car-rental',
    name: 'Car Rental',
    description: 'Explore the city at your own pace with a rental car',
    price: 10000,
    unit: '/day',
  },
]
